- name: "prep environment config file"
  copy:
    src: "{{ project_dir }}/deployment/inventories/{{ deploy_env }}/env"
    dest: "/etc/{{ project_artifact_name }}.conf"

- name: "start docker container"
  script: "../scripts/run.sh {{image_host_port}} {{project_artifact_name}} {{ bv }}"