- name: "prep environment config file"
  copy:
    src: "{{ project_dir }}/deployment/inventories/{{ deploy_env }}/env"
    dest: "/etc/{{ project_artifact_name }}.conf"

- name: start docker container for {{project_artifact_name}} on {{ ansible_ssh_host }}:{{hostvars[inventory_hostname].ansible_port}}
  script: "../scripts/run.sh {{image_host_port}} {{project_artifact_name}} {{ bv }}"