- name: show env vars
  debug: msg=" dir {{ project_dir }} and name {{ project_artifact_name }}"

- fail: msg="the variable 'project_dir' is not available"
  when: "project_dir is not defined"

- fail: msg="project_artifact_name is not defined"
  when: "project_artifact_name is not defined"

- name: "Check that the {{project_dir}} exists"
  stat:
    path: "{{project_dir}}"
  register: stat_result

- debug: msg="project_dir~{{project_dir}} with project_artifact_name~{{project_artifact_name}} exists~{{stat_result.stat.exists}}"

- name: build and promote app to docker
  shell: "{{ project_dir }}/deployment/{{ build_promotion_script }} {{ project_artifact_name }} {{ bv }}"
  when: ignore_docker_promotion|bool == false