---
- name: entrypoint play to aws
  hosts: localhost
  gather_facts: false

  roles:
    - { role: roles/build-api-harness,
        project_dir: "{{ PROJECT_DIR }}",
        harness_port: "{{ HARNESS_PORT }}",
        bv: "{{ PROJECT_IMAGE_VERSION }}"
      }
    - { role: roles/build-promote-java-app,
        project_dir: "{{ PROJECT_DIR }}",
        project_artifact_name: "{{ PROJECT_DIR | basename }}",
        build_promotion_script: "{{ BUILD_PROMOTE_SCRIPT | default('build_promote.sh') }}",
        project_image_version: "{{ PROJECT_IMAGE_VERSION }}",
        ignore_docker_promotion: false,
        bv: "{{ PROJECT_IMAGE_VERSION }}"
      }

- name: deploy image to app instance
  hosts: app-instance

  roles:
    - { role: roles/deploy-jar,
        project_dir: "{{ PROJECT_DIR }}" }
