---
- name: entrypoint play to aws
  hosts: localhost
  gather_facts: false

  roles:
    - { role: roles/build-api-harness,
        project_dir: "{{ PROJECT_DIR }}",
        harness_port: "8080:8080"
      }
    - { role: roles/build-springboot-app,
        project_dir: "{{ PROJECT_DIR }}",
        project_artifact_name: "{{ PROJECT_DIR | basename }}",
        build_promotion_script: "{{ BUILD_PROMOTE_SCRIPT | default('build_and_deploy_docker_image.sh') }}",
        project_image_version: "{{ PROJECT_IMAGE_VERSION }}",
        ignore_docker_promotion: True
      }

- name: deploy to app instances
  hosts: app-instance

  roles:
    - { role: roles/deploy-to-aws,
        project_dir: "{{ PROJECT_DIR }}" }
