---
- name: "verifying and building api harness and springboot java 11 app"
  hosts: localhost
  gather_facts: false

  roles:
    - { role: roles/build-api-harness,
        project_dir: "{{ PROJECT_DIR }}",
        harness_port: "{{ HARNESS_PORT | default('8081:8081') }}",
        bv: "{{ PROJECT_IMAGE_VERSION }}"
    }
    - { role: roles/build-promote-java-app,
        project_dir: "{{ PROJECT_DIR }}",
        project_artifact_name: "{{ PROJECT_DIR | basename }}",
        build_promotion_script: "{{ BUILD_PROMOTE_SCRIPT | default('build_promote.sh') }}",
        project_image_version: "{{ PROJECT_IMAGE_VERSION }}",
        ignore_docker_promotion: false,
        bv: "{{ PROJECT_IMAGE_VERSION }}"
    }

- name: include deploy to docker play
  include: promote-docker-image-to-env.yml