---
- name: entrypoint play
  hosts: localhost

  pre_tasks:
    - debug: msg="building spring_app {{PROJECT_DIR}} and {{PROJECT_ARTIFACT_JAR_NAME}}"

  roles:
    - { role: roles/build-springboot-app,
        project_dir: "{{ PROJECT_DIR }}",
        build_promotion_script: "{{ BUILD_PROMOTE_SCRIPT | default('build_and_deploy_docker_image.sh') }}",
        project_image_version: "{{ PROJECT_IMAGE_VERSION }}" }

    - { role: roles/k8s-deploy,
        project_dir: "{{ PROJECT_DIR }}",
        app_instance_count: "{{ APP_INSTANCE_COUNT | default(2)}}",
        app_namespace: "{{ APP_NAMESPACE | default('default') }}",
        project_image_version: "{{ PROJECT_IMAGE_VERSION }}" }

    - { role: roles/build-api-harness,
        harness_file_path: "{{ HARNESS_FILES_PATH }}",
        harness_mappings_path: "{{ HARNESS_MAPPINGS_PATH }}",
        harness_image_name: "{{ HARNESS_IMAGE_NAME | default('aloeda/aloeda-gateway-harness:v1') }}",
        harness_container_name: "{{ HARNESS_CONTAINER_NAME | default('aloeda-gateway-harness') }}",
        when: promote_api_harness|default(false)|bool == true }


