---
- hosts: all
  become: yes

  tasks:
    - name: Install Basic packages
      package:
        name: [ 'vim', 'zip', 'bash-completion', 'wget', 'tmux' ]
    - command: "sudo apt-get install openjdk-11-jre openjdk-11-jdk"