ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure("2") do |config|

  config.vm.synced_folder "./", "/x"
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "forwarded_port", guest: 8092, host: 8094
  config.vm.network "forwarded_port", guest: 3000, host: 3001

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yaml"
    ansible.verbose = true
  end
end