ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure("2") do |config|

  config.vm.synced_folder "./", "/"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 8092, host: 8093

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yaml"
    ansible.verbose = true
  end
end