---
- name: Provisioning a new Ubuntu 20+ Host
  hosts: all
  become: yes

  vars:
    default_password: "Saturn432$"
    users:
      - username: adeolaojo
        password: "{{ default_password }} | password_hash('sha512')"
      - username: funmi
        password: "{{ default_password }} | password_hash('sha512')"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4DgFZHKPIomcPfq2eX06Jvu8divVSJ5OXuIZ1G1OnjZAc9vc2Od5a2/BNM7Z2MH14qfiT3KMrfwwv+h+93w8cm8prjJIdI/W5UU49xnpDn4EO9gp087+uMITJ/rW7heZvJsp39bcaL+YBv3s9Fy1DZ2Pccmg7kcWdmFqvJFS8AzRGjfYLb0/OcfJgeENG22HAVlmlOGBZnG9GP8CR2Kgis2HOZBbYW/dc7clHAHg+uurHK5pfb4OAebBU/yIvs3H1oVn0EqZsBEK/IAawm7yWpIfkEqekFXE/II3akeiX8PJ86CMPW0Ql5ra7hzWau9qe2q30EzVHUDChP/36d2lWq/CpZwrWax/KX9KNWQyhBpv4gNXkVljaNOs2q5p0JK5Or8udGYUg1B8Qx2JWIqVZt1kNuo2+zmEDQF0y+SrGQLnZ99SlYbt0tmN2bRI44RXomD3ZHKLvKctxsPtdmwHap80VrbWlM92a2bhCR3bw8HWUGAVIcskwOBOLuOVQDgc= adeolaojo@adeolas-MacBook-Pro.local"

  tasks:
    - name: create and/or change username password
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        state: present
        shell: "/bin/bash"
      loop: "{{ users }}"

    - name: allow user to have passwordless sudo
      lineinfile:
        dest: "/etc/sudoers"
        line: '{{item.username}} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      loop: "{{ users }}"

    - name: copy ssh keys
      authorized_key:
        key: "{{ lookup('file', '/Users/adeolaojo/.ssh/id_rsa.pub') }}"
        user: "{{ item.username }}"
        state: present
        exclusive: False
      loop: "{{ users }}"

    - name: "print ubuntu os information"
      shell: "cat /etc/os-release"

    - name: "install basic os packages"
      package:
        name: [ 'vim', 'zip', 'bash-completion', 'wget', 'tmux' ]

    - name: "provision openjdk 11"
      script: "./scripts/install_java.sh"

    - name: "provision docker"
      script: "./scripts/install_docker.sh"
      tags: [ 'docker' ]

    - name: "provision postgres"
      script: "./scripts/install_postgres.sh"
      tags: [ 'postgres' ]

    - name: "provision grafana"
      script: "./scripts/install_grafana.sh"
      tags: "grafana"

    - name: "provision docker prometheus"
      script: "./scripts/install_prometheus.sh"
      tags: ["prometheus", "instrumentation"]

#    - name: "provision docker elk"
#      script: "./scripts/install_elk.sh"

    - name: "provision docker redis"
      script: "./scripts/install_redis.sh"

    - name: "provision ansible"
      script: "./scripts/install_ansible.sh"
      tags: ["ansible"]

    - name: "provision splunk"
      script: "./scripts/install_splunk.sh"
      tags: ["splunk", "instrumentation"]

    - name: "provision consul"
      script: "./scripts/install_consul.sh"
      tags: ["consul"]

    - name: "provision kafka + zookeeper"
      script: "./scripts/install_kafka.sh"
      tags: [ "kafka_zookeeper" ]