require 'json'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|

  config.vm.synced_folder "./", "/x"
  config.vm.box = "bento/ubuntu-20.04"

  # parse port configurations
  file = File.read('vagrant_config.json')
  vagrant_config = JSON.parse(file)

  vagrant_config["hosts"].each do |item|
    config.vm.network "forwarded_port", guest: item["guest"], host: item["host"]
  end

  config.vm.provision "shell", inline: <<-SHELL
      echo "sudo su -" >> .bashrc
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = vagrant_config["provision_script"]
    ansible.verbose = true
    ansible.tags = ENV['VAGRANT_TAG'] || nil
  end
end