- name: facts
  set_fact:
    project_image_version: "{{ project_image_version }}"

- name: build and deploy play
  block:
    - stat: path="{{project_dir}}"
      register: project_dir_stats

    - debug: msg="project_dir~{{ project_dir }} with project_dir_exists~{{ project_dir_stats.stat.exists }}"

    - name: build if project dir is available.
      shell: "(cd {{project_dir}} && chmod +x {{ role_path }}/scripts/build.sh && {{ role_path }}/scripts/build.sh {{ project_name }} {{ project_image_version }} {{ project_dir }})"
      when: "project_dir is defined and project_dir_stats.stat.exists == True and project_dir_stats.stat.isdir"

    - name: package build folder
      shell: "(cd {{ project_dir }} && tar -czvf package.tar.gz ./public)"
  when: "project_dir is defined"